services:
  golang-server-1:
    build:
      context: ./golang_server/
    ports:
      - "8881:8888"
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.5"
        reservations:
          memory: 128m
          cpus: "0.5"
    restart: always
    networks:
      - nginx
  golang-server-2-a:
    build:
      context: ./golang_server/
    ports:
      - "8882:8888"
    deploy:
      resources:
        limits:
          memory: 64m
          cpus: "0.25"
        reservations:
          memory: 64m
          cpus: "0.25"
    restart: always
    networks:
      - nginx

  golang-server-2-b:
    build:
      context: ./golang_server/
    ports:
      - "8883:8888"
    deploy:
      resources:
        limits:
          memory: 64m
          cpus: "0.25"
        reservations:
          memory: 64m
          cpus: "0.25"
    restart: always
    networks:
      - nginx

  openresty:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - nginx

networks:
  nginx:
